* template for c++ projects
The template folder contains the project structure.
Clone this repository and rename the template folder to your project name.
** build files
Boost.Build and CMake build files are available.
*** Boost.Build
mkdir build_boost
**** build lib
b2 --build-dir=./build_boost -q toolset=gcc lib//lib
**** execute lib test
b2 --build-dir=./build_boost -q toolset=gcc lib//test
**** build application executeable
b2 --build-dir=./build_boost -q toolset=gcc app//exe
**** run application executeable
b2 --build-dir=./build_boost -q toolset=gcc app//run
*** CMake
mkdir build_cmake
cmake -B ./build_cmake
cmake --build ./build_cmake
*** execute test and app
cmake --build ./build_cmake --target test
**** execute test and app with ctest
cd build_cmake && ctest -V
ctest -R 'app::exe' -V
ctest -R 'lib::test' --output-on-failure
** formatting
*** Clang-Format file is available.
*** cmake-format configuration
see [[https://github.com/cheshirekow/cmake_format][cmake-format]]
execute with: find . -type f -name 'CMakeLists.txt' -execdir cmake-format -i {} \;
